
  - name: Download Java
    get_url: url=http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm dest=. headers='Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

  - name: Copy rpm file to server
    copy:
      src: jdk-8u131-linux-x64.rpm
      dest: /tmp/jdk-8u131-linux-x64.rpm

  - name: Install Java
    yum:
      name: /tmp/jdk-8u131-linux-x64.rpm
      state: present
